import { Configuration, OpenAIApi } from 'openai-edge';
import { OpenAIStream, StreamingTextResponse } from 'ai';
 
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(config);
 
export const runtime = 'edge';
 
export async function POST(req) {
  const { messages } = await req.json();
 
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo-16k',
    stream: true,
    max_tokens: 12000,
    temperature: 0.6,
    messages: [
        {
          role: "system",
          content: `You are a smart assistant that can help users create a landing page. Please follow the following rules:
- Users will provide a description of the website they want
- You will make a website based on the available components
- You are free to mix several HTML Elements to fulfill a good landing page structure
- Set copywriting according to user requirements
- Include this css file in head: ${process.env.NEXT_PUBLIC_APP_URL}/app.css
- Include this js file in body: https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js & https://unpkg.com/alpinejs
- Don't include any external css & js (except the one just requested)
- Use inline css only if user request for specific design like color/font size/etc
- Give response in html code

HTML Elements:
- Navbar (Simple): <nav class="nav-simple"><div class="nav-container"><a href="#">Home</a><a href="#">Features</a><a href="#">Pricing</a><a href="#">Blog</a><a class="class-a-7" href="#"><iconify-icon icon="fa6-brands:behance"></iconify-icon></a><a class="class-a-8" href="#"><iconify-icon icon="fa6-brands:dribbble"></iconify-icon></a></div></nav>
- Navbar (Commerce): <nav class="nav-commerce" x-data="{ isOpen: false }"><div class="nav-container"><div class="between"><a class="brand" href="#">Brand</a><div class="mob-btn"><button x-cloak="null" @click="isOpen = !isOpen" type="button" aria-label="toggle menu"><iconify-icon width="24px" icon="heroicons-outline:menu" x-show="!isOpen"></iconify-icon><iconify-icon width="24px" icon="heroicons-outline:x" x-show="isOpen"></iconify-icon></button></div></div><div class="menu" x-cloak="null" :class="[isOpen ? 'translate-x-0 opacity-100 ' : 'opacity-0 -translate-x-full']"><div class="list"><a href="#">Home</a><a href="#">Shop</a><a href="#">Contact</a><a href="#">About</a></div><div class="cart"><a href="#"><iconify-icon width="20px" icon="heroicons-outline:shopping-cart"></iconify-icon><span></span></a></div></div></div></nav>
- Navbar (Search): <nav class="nav-search" x-data="{ isOpen: false }"><div class="nav-container"><div class="between"><a class="brand" href="#">Brand</a><div class="mob-btn"><button x-cloak="null" @click="isOpen = !isOpen" type="button" aria-label="toggle menu"><iconify-icon width="24px" icon="heroicons-outline:menu" x-show="!isOpen"></iconify-icon><iconify-icon width="24px" icon="heroicons-outline:x" x-show="isOpen"></iconify-icon></button></div></div><div class="menu" x-cloak="null" :class="[isOpen ? 'translate-x-0 opacity-100 ' : 'opacity-0 -translate-x-full']"><div class="list"><a href="#">Home</a><a href="#">About</a><a href="#">Contact</a></div><div class="div-search"><span><iconify-icon width="20px" icon="heroicons-outline:search"></iconify-icon></span><input type="text" placeholder="Search"></div></div></div></nav>
- Hero (2 Columns): <header class="hero-2col"><div class="hero-container"><div class="hero-wrap"><div class="hero-left"><div class="left-wrap"><h1>Best place to choose<br>your<span>clothes</span></h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro beatae error laborum ab amet sunt recusandae? Reiciendis natus perspiciatis optio.</p><button>Shop Now</button></div></div><div class="hero-right"><img src="https://i.postimg.cc/SKQg78K2/Catalogue-pana-1.png" alt="Hero"></div></div></div></header>
- Hero (Newsletter): <header class="hero-newsletter"><div class="hero-container"><div class="hero-wrap"><div class="hero-left"><div class="left-wrap"><h1>Subscribe To The<span>Newsletter</span></h1><p>be the first to knows when our<span>Brand</span>is live</p><div class="form"><input id="email" type="text" placeholder="Email Address"><button>Subscribe</button></div></div></div><div class="hero-right"><img src="https://i.postimg.cc/d0MqhsQx/campaign.png" alt="email illustration vector art"></div></div></div></header>
- Hero (Center): <section class="hero-center"><div class="hero-container"><div class="hero-top"><h1>Building Your Next App with our Awesome components</h1><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero similique obcaecati illum mollitia.</p><button>Start 14-Day free trial</button><p class="sm">No credit card required</p></div><div class="hero-bottom"><img src="https://i.postimg.cc/s1FnpNBs/event.webp"></div></div></section>
- Hero (Full BG): <header class="hero-full-bg"><div class="hero-container"><div class="hero-wrap"><div class="tc"><h1>Build your new<span>Saas</span>Project</h1><button>Start project</button></div></div></div></header>
- Features (Simple): <section class="ft-simple"><div class="ft-container"><div class="ft-grid"><div class="ft-box"><iconify-icon width="32px" icon="heroicons-outline:code"></iconify-icon><h4>Default Taiwindcss Config</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim fusce tortor, ac sed malesuada blandit. Et mi gravida sem feugiat.</p></div><div class="ft-box"><iconify-icon width="32px" icon="heroicons-outline:desktop-computer"></iconify-icon><h4>Fully Responsive Components</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim fusce tortor, ac sed malesuada blandit. Et mi gravida sem feugiat.</p></div><div class="ft-box"><iconify-icon width="32px" icon="heroicons-outline:flag"></iconify-icon><h4>RTL Languages Support</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dignissim fusce tortor, ac sed malesuada blandit. Et mi gravida sem feugiat.</p></div></div></div></section>
- Features (Bordered Box): <section class="ft-border"><div class="ft-container"><h2>Explore our<br>awesome<span>Components</span></h2><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nostrum quam voluptatibus</p><div class="ft-grid"><div class="ft-box"><span><iconify-icon width="32px" icon="heroicons-outline:eye"></iconify-icon></span><h3>elegant Dark Mode</h3><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident ab nulla quod dignissimos vel non corrupti doloribus voluptatum eveniet</p><a href="#"><iconify-icon width="24px" icon="heroicons-outline:arrow-circle-right"></iconify-icon></a></div><div class="ft-box"><span><iconify-icon width="32px" icon="heroicons-outline:puzzle"></iconify-icon></span><h3>Easy to customiztions</h3><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident ab nulla quod dignissimos vel non corrupti doloribus voluptatum eveniet</p><a href="#"><iconify-icon width="24px" icon="heroicons-outline:arrow-circle-right"></iconify-icon></a></div><div class="ft-box"><span><iconify-icon width="32px" icon="heroicons-outline:cursor-click"></iconify-icon></span><h3>Simple & clean designs</h3><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident ab nulla quod dignissimos vel non corrupti doloribus voluptatum eveniet</p><a href="#"><iconify-icon width="24px" icon="heroicons-outline:arrow-circle-right"></iconify-icon></a></div></div></div></section>
- Portfolio (Simple): <section class="portfolio"><div class="p-container"><h1>Portfolio</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nostrum quam voluptatibus</p><div class="p-grid"><div class="p-item"><img src="https://i.postimg.cc/GpsxjQCp/port-1.webp" alt=""><h2>Best website collections</h2><p>Website</p></div><div class="p-item"><img src="https://i.postimg.cc/RF5QpHSL/port-2.webp" alt=""><h2>Block of Ui kit collections</h2><p>Ui kit</p></div><div class="p-item"><img src="https://i.postimg.cc/YCPxgPTV/port-3.webp" alt=""><h2>Ton's of mobile mockup</h2><p>Mockups</p></div></div></div></section>
- Pricing (Simple): <div class="pr-simple"><div class="pr-container"><h1>Pricing Plan</h1><p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Alias quas magni libero consequuntur voluptatum velit amet id repudiandae ea, deleniti laborum in neque eveniet.</p><div class="pr-grid"><div class="pr-box"><p>FREE</p><h2>$0</h2><p>Life time</p><button>Start Now</button></div><div class="pr-box-featured"><p>PREMIUM</p><h2>$40</h2><p>Per month</p><button>Start Now</button></div><div class="pr-box"><p>ENTERPRISE</p><h2>$100</h2><p>Life time</p><button>Start Now</button></div></div></div></div>
- Pricing (List): <div class="pr-simple"><div class="pr-container"><h1>Pricing Plan</h1><p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Alias quas magni libero consequuntur voluptatum velit amet id repudiandae ea, deleniti laborum in neque eveniet.</p><div class="pr-grid"><div class="pr-box"><p>FREE</p><h2>$0</h2><p>Life time</p><button>Start Now</button></div><div class="pr-box-featured"><p>PREMIUM</p><h2>$40</h2><p>Per month</p><button>Start Now</button></div><div class="pr-box"><p>ENTERPRISE</p><h2>$100</h2><p>Life time</p><button>Start Now</button></div></div></div></div>
- Testimonials (Simple): <section class="testi-simple"><div class="testi-container"><h2>What our<span>clients</span>say</h2><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p><section class="testi-grid"><div class="testi-box"><p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore quibusdam ducimus libero ad tempora doloribus"</p><div class="profile"><img src="https://i.postimg.cc/dVDVpNDJ/ava-1.webp" alt=""><div class="name"><h1>Robert</h1><span>CTO, Robert Consultency</span></div></div></div><div class="testi-box"><p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore quibusdam ducimus libero ad tempora doloribus"</p><div class="profile"><img src="https://i.postimg.cc/c4FJDGxD/ava-2.webp" alt=""><div class="name"><h1>Jeny Doe</h1><span>CEO, Jeny Consultency</span></div></div></div><div class="testi-box"><p>“Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore quibusdam ducimus libero ad tempora doloribus"</p><div class="profile"><img src="https://i.postimg.cc/8Pp5BzSJ/ava-3.webp" alt=""><div class="name"><h1>Ema Watson</h1><span>Marketing Manager at Stech</span></div></div></div></section></div></section>
- Contact (Simple): <section class="contact-simple"><div class="c-container"><div class="c-title"><p>Contact us</p><h1>Get in touch</h1><p>Our friendly team is always here to chat.</p></div><div class="c-grid"><div class="c-item"><span class="s-wrap"><iconify-icon width="28px" icon="heroicons-outline:mail"></iconify-icon></span><h2>Email</h2><p>Our friendly team is here to help.</p><p class="val">hello@merakiui.com</p></div><div class="c-item"><span class="s-wrap"><iconify-icon width="28px" icon="heroicons-outline:map"></iconify-icon></span><h2>Office</h2><p>Come say hello at our office HQ.</p><p class="val">100 Smith Street Collingwood VIC 3066 AU</p></div><div class="c-item"><span class="s-wrap"><iconify-icon width="28px" icon="heroicons-outline:phone"></iconify-icon></span><h2>Phone</h2><p>Mon-Fri from 8am to 5pm.</p><p class="val">+1 (555) 000-0000</p></div></div></div></section>
- Footer (Simple): <footer class="f-simple"><div class="f-container"><a class="brand" href="#">Brand Name</a><p>© Copyright 2023. All Rights Reserved.</p><div class="social"><a href="#"><iconify-icon width="20px" icon="fa6-brands:reddit"></iconify-icon></a><a href="#"><iconify-icon width="20px" icon="fa6-brands:facebook"></iconify-icon></a><a href="#"><iconify-icon width="20px" icon="fa6-brands:github"></iconify-icon></a></div></div></footer>`
        },
        ...messages,
      ],
  });
  const stream = OpenAIStream(response);
  return new StreamingTextResponse(stream);
}